run_env: DEV # DEV, TEST, STAGING or PROD
server_secret_key: 'ServerKey!!!'
sql_alchemy:
  create_tables: True # If true, execute table creation command on app start
  database_uri: 'sqlite:///:memory:'
  track_modifications: False
elasticsearch:
  dry_run: True # If True, I will just print the data and not send anything to elasticsearch
  host: 'http://wp-p1m-50.ebi.ac.uk:9200'
admin_username: 'admin'
admin_password: '123456'